// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD08FQDguypG8I9YFYxJOYwv54B0imRgU0',
    appId: '1:1099217509932:android:684c44780caccb15cd3b89',
    messagingSenderId: '1099217509932',
    projectId: 'chatapp-66c4e',
    storageBucket: 'chatapp-66c4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvSyt8o80OmcyD3XI7nAfSMf2JqYUcTiI',
    appId: '1:1099217509932:ios:d151ee39a6db4cd8cd3b89',
    messagingSenderId: '1099217509932',
    projectId: 'chatapp-66c4e',
    storageBucket: 'chatapp-66c4e.firebasestorage.app',
    androidClientId: '1099217509932-u9bc8m7gifsa81b76bcrk2a32ucardt1.apps.googleusercontent.com',
    iosClientId: '1099217509932-icnpiphjuo1v4sgtee2b1puuag29mqv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );
}
